### ISSUE TITLE
Computation of SJV

### ISSUE THREAD

**Issue by Alessiobrini** [BayerSe/RealizedQuantities#1]
I have a doubt about the way the signed jump variation is computed. You cite [Patton and Sheppard](https://public.econ.duke.edu/~ap172/Patton_Sheppard_REStat_2015.pdf), in which sjv is computed as simply the difference between the positive and the negative realized semivariances.

Why do you compute such quantity as `sjv = rv_p ** 0.5 - rv_n ** 0.5`?

**Comment by BayerSe** [comment]
You're right, thanks for pointing this out. Now computing `sjv = rv_p - rv_n`
